name: Automation Tests

on:
  schedule:
    - cron: '1 9 * * *'
    - cron: '3 9 * * *'

jobs:
  ui-chrome-smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Smoke Test
        if: github.event.schedule == '1 9 * * *'
        run: |
          echo "${{ github.event.schedule }}"
        
  ui-chrome-sanity-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Sanity Test
        if: github.event.schedule == '3 9 * * *'
        run: |
          echo "hii ${{ github.event.schedule }}"
  
  ui-chrom-sanity-tests:
    runs-on: ubuntu-latest
    steps:
      - name: anity Test
        run: |
          echo "hii ${{ github.event.schedule }}"
        
