name: Automation Tests

on:
  # schedule:
  #   - cron: '* * * * *'

jobs:
  ui-chrome-smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Smoke Test
        if: github.event.schedule == '40 13 * * *'
        run: |
          echo "${{ github.event.schedule }}"
        
  ui-chrome-sanity-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Sanity Test
        if: github.event.schedule == '35 12 * * *'
        run: |
          echo "hii ${{ github.event.schedule }}"
  
  ui-chrom-sanity-tests:
    runs-on: ubuntu-latest
    steps:
      - name: anity Test
        run: |
          echo "hii ${{ github.event.schedule }}"
        
