name: Automation Tests

on:
  schedule:
    - cron: '55 9 * * *'
    - cron: '57 9 * * *'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.step1.outputs.runner }}
    steps:
      - name: Check branch
        id: step1
        run: |
          if [ ${{ github.event.schedule }} == '55 9 * * *' ]; then
            echo "runner=ubuntu-latest" >> $GITHUB_OUTPUT
          elif [ ${{ github.event.schedule }} == '57 9 * * *' ]; then
            echo "runner=macos-latest" >> $GITHUB_OUTPUT
          fi

  job1:
    needs: [setup]
    runs-on: ${{ needs.setup.outputs.runner }}
    steps:
      - run: echo "My runner is ${{ needs.setup.outputs.runner }}" #ubuntu-latest if main branch
  
      
