name: Automation Tests

on:
  schedule:
    - cron: '10 12 * * *'
    - cron: '12 12 * * *'

jobs:
  ui-chrome-smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Smoke Test
        if: github.event.schedule == '10 12 * * *'
        run: |
          echo "${{ github.event.schedule }}"
        
  ui-chrome-sanity-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Sanity Test
        if: github.event.schedule == '12 12 * * *'
        run: |
          echo "hii ${{ github.event.schedule }}"
  
  ui-chrom-sanity-tests:
    runs-on: ubuntu-latest
    steps:
      - name: anity Test
        run: |
          echo "hii ${{ github.event.schedule }}"
        
