name: Automation Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '11 10 * * *'
    - cron: '13 10 * * *'

jobs:
  ui-chrome-smoke-tests:
    runs-on: ubuntu-latest
    steps:
      # - name: Smoke Test
      #   if: github.event.schedule == '17 9 * * *'
      #   run: |
      #     echo "${{ github.event.schedule }}"

      # - name: Sanity Test
      #   if: github.event.schedule == '15 9 * * *'
      #   run: |
      #     echo "hii ${{ github.event.schedule }}"
       
      # - name: anity Test
      #   run: |
      #     echo "hii ${{ github.event.schedule }}"

      - name: Print UTC Time
        run: |
          if [[ $github.event.schedule == '11 10 * * *' ]]; then
            echo "ACCOUNT_ID=1234" >> "$GITHUB_ENV"
          elif [[ $github.event.schedule == '13 10 * * *' ]]; then
            echo "ACCOUNT_ID=6789" >> "$GITHUB_ENV"
          fi
      - name: Check
        run: |
          echo "$ACCOUNT_ID"
        
      
