name: Automation Tests

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '40 12 * * *'
  #   - cron: '43 12 * * *'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.step1.outputs.runner }}
    steps:
      - name: Check branch
        id: step1
        run: |
          if [[ $github.event.schedule == '40 12 * * *' ]]; then
            echo "Hiiiiiiiiiiiiiiiiii"
            echo "runner=ubuntu-latest" >> $GITHUB_OUTPUT
          elif [[ $github.event.schedule == '43 12 * * *' ]]; then
            echo "Byeeeeeeeeeeeeeeeee"
            echo "${{ github.event.schedule }}"
            echo "runner=macos-latest" >> $GITHUB_OUTPUT
          fi

  job1:
    needs: [setup]
    runs-on: ${{ needs.setup.outputs.runner }}
    steps:
      - run: echo "My runner is ${{ needs.setup.outputs.runner }}" #ubuntu-latest if main branch
  
      
