name: Automation Tests

on:
  schedule:
    - cron: '0 12 * * *'
    - cron: '2 12 * * *'

jobs:
  ui-chrome-smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Smoke Test
        if: github.event.schedule == '0 12 * * *'
        run: |
          echo "${{ github.event.schedule }}"
        
  ui-chrome-sanity-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Sanity Test
        if: github.event.schedule == '02 12 * * *'
        run: |
          echo "hii ${{ github.event.schedule }}"
  
  ui-chrome-sanity-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Sanity Test
        run: |
          echo "hii ${{ github.event.schedule }}"
        
