name: Automation Tests

on:
  workflow_dispatch:
  schedule:
    - cron: ‘55 11 * * *’
    - cron: ‘56 11 * * *’

jobs:
  ui-chrome-smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Smoke Test
        if: github.event.schedule == '55 11 * * *'
        run: |
          echo "${{ github.event.schedule }}"
        
  ui-chrome-sanity-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Sanity Test
        if: github.event.schedule == '56 11 * * *'
        run: |
          echo "hii ${{ github.event.schedule }}"
        
