name: Automation Tests

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.step1.outputs.runner }}
    steps:
      - name: Check branch
        id: step1
        run: |
          if [ ${{ github.ref }} == 'refs/heads/main' ]; then
            echo "runner=ubuntu-latest" >> $GITHUB_OUTPUT
          else
            echo "runner=macos-latest" >> $GITHUB_OUTPUT
          fi

  job1:
    needs: [setup]
    runs-on: ${{ needs.setup.outputs.runner }}
    steps:
      - run: echo "My runner is ${{ needs.setup.outputs.runner }}" #ubuntu-latest if main branch
  
      
